theme: jekyll-theme-minimal
auto_dark_mode: true
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: "EC M202A Project - Lights Under Attack: Stress-Testing Noise-Coded Illumination"
description: "Course project website for EC M202A / CS M213A (Fall 2025)"
url: "https://nci.mwjung.com"

markdown: kramdown
kramdown:
  input: GFM

# Necessary for GitHub Pages
plugins: []